#!/bin/bash

# outpost-init

if [ ! -d ~/.outpost ]
then
    git clone https://github.com/kr-b/outpost ~/.outpost
else
    cd ~/.outpost && git pull
fi

elif [ "$SHELL" == "/bin/bash" ]; then
    echo "export PATH=\"\$PATH:\$HOME/.outpost/tools\"" >> ~/.bashrc
else
    echo "[!] Please add ~/.outpost/tools to your \$PATH"
    echo "(export PATH=\"\$PATH:$HOME/.outpost/tools\")"
fi 